DATASET_NAME: ""
DATASET_DRIVE_ID: ""
SUBSCRIPTION_ID: ""
RESOURCE_GROUP: ""
ACCOUNT_NAME: ""
ACCOUNT_KEY: ""
CONTAINER_NAME: ""
WORKSPACE_NAME: ""
DATASTORE_NAME: ""
COMPUTE_NAME: ""
COMPUTE_NAME_INFERENCE: ""
